mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
)

polls/urls.py
from django.conf.urls import patterns, url, include

from . import views


urlpatterns = patterns('',

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
    url(r'createpoll/save/$', views.savePoll, name='vote'),
    url(r'createpoll/$', views.createPoll, name='vote'),
    url(r'votepoll/(?P<poll_id>\d+)$', views.votePoll, name='vote'),
    url(r'votepoll/(?P<poll_id>\d+)/save$', views.vote, name='vote'),
)

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now())
    user_id = models.CharField(max_length=200)
    poll_id = models.AutoField(primary_key=True)

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.question

    def was_published_recently(self):
        now = timezone.now()
        return True

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.choice_text


class PollHistory(models.Model):
    user_id = models.CharField(max_length=200)
    poll_id = models.ForeignKey(Poll)
    pass

polls/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.views import generic
import time
from .models import Choice, Poll, PollHistory
from django.contrib.auth.decorators import login_required
import json
from django.db import transaction, connection
from django.views.decorators.csrf import csrf_exempt

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Poll.objects.order_by('-pub_date')[:5]



class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'


# def canVote(poll_id, user_id):
@login_required
def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    ph = PollHistory.objects.filter(poll_id = p, user_id = request.user.id)
    if len(ph) > 0:
        return HttpResponseRedirect(reverse('polls:results', args=(p.poll_id,)))
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'polls/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        with transaction.atomic():
            selected_choice.votes += 1
            selected_choice.save()
            PollHistory(poll_id = p, user_id = request.user.id).save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.poll_id,)))

@login_required
def savePoll(request):
    user_id = request.user.id
    print user_id
    ques_data = json.loads(request.POST['data'])['create']
    ques_title = ques_data['ques']
    ques_opt = ques_data['opt']
    check_len = [True for sin_opt in ques_opt if len(sin_opt) > 300]
    if True in check_len or len(ques_opt) < 2:
        return HttpResponse(json.dumps({"success": False, 'data': "Option Length should be less than 300 and minimum options should be 2"}))
    with transaction.atomic():
        q = Poll(question=ques_title, user_id=user_id)
        q.save()
        for sin_choice in ques_opt:
            c = Choice(poll=q, choice_text=sin_choice)
            c.save()
    return HttpResponse(json.dumps({"success":True,'data':[]}))

@login_required
def createPoll(request):
    return render(request, 'polls/create_poll.html', {})
    pass

@login_required
def votePoll(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    ch = Choice.objects.filter(poll_id=p)
    ph = PollHistory.objects.filter(poll_id=p, user_id=request.user.id)
    if len(ph) > 0:
        return HttpResponseRedirect(reverse('polls:results', args=(p.poll_id,)))

    # ques = Poll.objects.get(poll_id=p)
    return render(request, 'polls/vote_poll.html', {
        'choices': ch,
        'question': p.question
    })

@login_required
def view_result(request):
    pass

polls/templates/polls/create_poll.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Poll</title>
</head>
<body>
<div id="createpoll"> {% csrf_token %}
<span>Enter Poll Title</span><br>
<input type="text" id="ques_title"><br>
<span>Enter Poll Options</span><br>
1. <input id="ques_options"><br><br>
</div>
<br>
<br>
<button type="button" onclick="createPoll.init.addOption()">Add more option</button>
<button type="button" onclick="createPoll.init.processForm()">Submit</button>
<br>
<br>
<span id="alert_box"></span>
</body>
<script type="text/javascript" src="/static/binding.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
</html>

polls/templates/polls/detail.html
<a href="/polls/">View All Polls</a>


<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' poll.poll_id %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for poll in latest_question_list %}
		<li><a href="/polls/votepoll/{{ poll.poll_id }}">{{ poll.question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
<a href="/polls/createpoll/">Create New Poll</a>

polls/templates/polls/results.html
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

polls/templates/polls/vote_poll.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ question }}</title>
</head>
<body>
<a href="/polls/">View All Polls</a>
<br>
<br>
<div>{{ question }}</div>
<form action="/polls/votepoll/{{choices.0.poll_id}}/save" method="post">
{% csrf_token %}
{% for choice in choices %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.poll_id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
</body>
</html>